// The nine holes. Each map is drawn as seen in the overview, the tee near
// the bottom. One character per tile:
//
//   .  green          T  tee           O  cup          o  round bumper
//   s  sand           ~  water         :  open drop    X  block
//   1 2 3 4  green with the top-left, top-right, bottom-right or bottom-left
//            corner cut off by a diagonal border
//   (space)  outside the course
//
// Wooden borders go wherever the course meets the outside or a block; water
// and drops have none. Terrain is a list of smooth ramps (along u or v,
// optionally limited to a band of the other axis) and round hills, in map
// coordinates. Movers are spinners (a bar turning around a post, speed in
// radians per second) and sliders (a block gliding between two points).

export const HOLES = [
  {
    name: 'First Putt',
    par: 2,
    flag: 0xff4f5e,
    map: [
      '1...2',
      '.....',
      '..O..',
      '.....',
      '.....',
      '.....',
      '.....',
      '.....',
      '.....',
      '.....',
      '..T..',
      '.....',
      '4...3',
    ],
  },
  {
    name: 'Dogleg',
    par: 3,
    flag: 0xffc12e,
    map: [
      '1........2',
      '..........',
      '.O........',
      '4.........',
      '     4....',
      '      ....',
      '      ....',
      '      ....',
      '      ....',
      '      ....',
      '      .T..',
      '      4..3',
    ],
  },
  {
    name: 'Bumper Garden',
    par: 3,
    flag: 0x4fa3ff,
    map: [
      ' 1.....2 ',
      '1...O...2',
      '.........',
      '...XXX...',
      '.........',
      '..o...o..',
      '.........',
      '....o....',
      '.o.....o.',
      '.........',
      '.........',
      '.........',
      '4...T...3',
      ' 4.....3 ',
    ],
  },
  {
    name: 'The Plateau',
    par: 3,
    flag: 0xb77bff,
    map: [
      ':::::::',
      ' ..... ',
      ' ..O.. ',
      ' ..X.. ',
      ' ..... ',
      '.......',
      '.......',
      '.......',
      '.......',
      '.......',
      '.......',
      '...T...',
      '4.....3',
    ],
    terrain: [{ ramp: 'v', from: 9, to: 5, dh: 0.9 }],
  },
  {
    name: 'Turnstile',
    par: 3,
    flag: 0xff8a3d,
    map: [
      '1.....2',
      '.....O.',
      '.......',
      '.......',
      'XX...XX',
      '.......',
      '.......',
      '.......',
      '.......',
      '.......',
      '.......',
      '.......',
      '.......',
      '...T...',
      '4.....3',
    ],
    movers: [{ spin: [3.5, 8], len: 2.3, speed: 1.3 }],
  },
  {
    name: 'Lily Pond',
    par: 3,
    flag: 0xff5fb0,
    map: [
      '1.......2',
      '.........',
      '.......O.',
      '.........',
      '~..~~~~~~',
      '~..~~~~~~',
      '~..~~~~~~',
      '~..~~~~~~',
      '.........',
      '.........',
      '..T......',
      '4.......3',
    ],
  },
  {
    name: 'Sliding Gate',
    par: 3,
    flag: 0x3fd28a,
    map: [
      '1.........2',
      '..O........',
      '...sss.....',
      '4..sss.....',
      '     4.....',
      '      .....',
      '      .....',
      '     1.....',
      '1..........',
      '...........',
      '..T........',
      '4.........3',
    ],
    movers: [{ slide: [7.74, 6, 9.26, 6], size: [2.4, 0.5], period: 3 }],
  },
  {
    name: 'Volcano',
    par: 3,
    flag: 0xff3d3d,
    map: [
      '1.........2',
      '...........',
      '...........',
      '...........',
      '.....O.....',
      '...........',
      '...........',
      '...........',
      '..o.....o..',
      '...........',
      '...........',
      '.....T.....',
      '4.........3',
    ],
    terrain: [
      { hill: [5.5, 4.5], r: 3.4, dh: 0.85 },
      { hill: [5.5, 4.5], r: 0.6, dh: -0.04 },
    ],
  },
  {
    name: 'Grand Tour',
    par: 4,
    flag: 0xffd84a,
    map: [
      '1...........2',
      '.............',
      '.............',
      '.............',
      '....3   4....',
      '....     ....',
      '....     ....',
      '....     ....',
      '.o..     ....',
      '....     ....',
      '....     ....',
      '..o.     .~..',
      '....     .~..',
      '....     ....',
      '....     ..O.',
      '..T.     ....',
      '....     ....',
      '4..3     4..3',
    ],
    terrain: [{ ramp: 'v', from: 10, to: 6, dh: 0.6 }],
    movers: [{ spin: [6.5, 2], len: 1.4, speed: -1.6 }],
  },
];
